### PR TITLE
Support localizable `File` for `IASKAppSettingsWebViewController`

### PR DESCRIPTION
**Pull request by funnel20**
Resolves issue https://github.com/futuretap/InAppSettingsKit/issues/510

### CODE REVIEW

**Comment by futuretap** [comment]
Good idea to support localization for the File parameter. However, we should use IASK's own localization scheme (`localizedObjectForKey:` instead of `NSLocalizedString()`. Then the localized URLs are in the same localized string files than the rest of the settings keys.

**Comment by funnel20** [comment]
You're absolutely right, I jumped too fast to conclusions.
Then I need your help a bit, I don't know the exact coding style that you prefer. Or you can make the improvement yourself.

**Comment by futuretap** [comment]
Replacing `NSLocalizedString(specifier.file, nil)` with `[specifier localizedObjectForKey:kIASKFile]` should do it.

**Comment by funnel20** [comment]
> Replacing `NSLocalizedString(specifier.file, nil)` with `[specifier localizedObjectForKey:kIASKFile]` should do it.

Done

**Pull request merged**
