### PR TITLE
Reload localization string when language changed

### PR DESCRIPTION
**Pull request by hklsk**

### CODE REVIEW

**Comment by futuretap** [comment]
Why should this be useful? When the system language is changed, all apps are killed and have to be relaunched anyway.

**Comment by hklsk** [comment]
Because I provide option for user to select the language in the app, when the language change the language in app, reload it

**Comment by futuretap** [comment]
Hm, doesn't feel right to add this at this level. I don't want to circumvent the system provided localization facilities and reinvent the wheel. Just to allow in-app language switching which is not recommended by Apple anyway. Closing this PR for now.

**Comment by vanderneut** [comment]
I've built in-app language switching in our app. No changes are needed for that in the existing InAppSettingsKit. I agree that this is not a feature that needs to be added to InAppSettingsKit itself. And by the way, the app doesn't have to be reloaded just to change the UI language.

**Comment by futuretap** [comment]
I know, but it's clearly not supported by Apple and easy to forget view refreshes, especially when storyboards are already loaded.

**Pull request closed without merging**
