### PR TITLE
Add Travis to the project

### PR DESCRIPTION
**Pull request by wkoszek**
We should see if the pull requests are fine through the Travis wiring.

Example of the successful build:

https://travis-ci.org/wkoszek/InAppSettingsKit/builds/143246550

@futuretap Unsure if you guys use Travis, so just in case: you'd have to setup and account and wire the futuretap's InAppSettingsKit repo in there. The README.md already has a badge pointing to your repo.

### CODE REVIEW

**Comment by futuretap** [comment]
I've never used it so I don't know how this all works and what implications it has. For instance, does it automatically build & test each pull request?

**Comment by wkoszek** [comment]
@futuretap Yeah. If you decide to integrate Travis in the repo, you'll see Travis building IASK on each commit (and executing whatever is in .travis.yml) and pull requests will get built too.

**Comment by futuretap** [comment]
Thanks, I'll take a look when I've some more time to spare.

**Comment by wkoszek** [comment]
@futuretap Sounds good. From my personal experience there's no harm. There's an additional advantage, since people generally have more "trust" in green Travis badge signalising that project is building. I've also hooked up unit tests, so there's something valuable there.

**Comment by diederich** [comment]
Superseeded by #415.
🙏 @wkoszek

**Pull request closed without merging**
