### PR TITLE
Add Carthage support

### LINKED ISSUE #308: Add Carthage support
Project currently does not build with Carthage.

Fixing this would require adding a framework target with a shared build scheme.

### PR DESCRIPTION
**Pull request by pcantrell**
Fixes #308.

### CODE REVIEW

**Comment by mattijsf** [comment]
+1
It doesn't break CocoaPod support and it adds support for the new Carthage build system that gains more and more popularity. I'd say a win-win. Please merge this!

**Comment by pcantrell** [comment]
@mattijsf: It’s unclear whether this project is actively maintained at the moment, since this PR has been sitting around for 3 months, but if you want to use Carthage right away you can point at my fork until @futuretap gets around to merging it:

    github "pcantrell/InAppSettingsKit" "carthage"

**Comment by futuretap** [comment]
I'm sorry that this is open for so long already. I'm not using Carthage myself and haven't tested it. Judging the comments here it seems to work fine though. Can you do me a favor and add a short bit in the Readme to describe the Carthage installation? Then I'll gladly pull it.

**Comment by pcantrell** [comment]
Added Carthage docs. Cocoapods wasn’t documented either, so I added that. I also refactored the README a bit to keep things comprehensible.

**Pull request merged**
