### PR TITLE
Post self as object with kIASKAppSettingChanged NSNotification

### PR DESCRIPTION
**Pull request by GarethShapiro**

### CODE REVIEW

**Comment by 0xced** [comment]
That change was a bad surprise when I upgraded from version 2.6 to 2.8. My code crashed as it expected a NSString but got an IASKMultipleValueSelection object instead. 😕

I think a breaking change like this should have warranted a major version bump, i.e. version 3.0.

By the way, there’s one [remaining object as key](https://github.com/futuretap/InAppSettingsKit/blob/2.8/InAppSettingsKit/Controllers/IASKAppSettingsViewController.m?ts=4#L950) instead of object as IASKAppSettingsViewController.

**Comment by futuretap** [comment]
Sorry about that, Cédric. It's a tricky issue indeed. Functionality-wise the delta didn't justify a 3.0 and I fear even then some people would have run into the issue. And on IASK side there's not really a way of checking if some callers would have been affected. Now of course we could have changed the notification name but that's not ideal either.

Will look into the remaining postNotification, thanks.

**Comment by 0xced** [comment]
Not a big deal, I caught it before shipping! 😉

@GarethShapiro: I wonder what was the motivation behind this change. Why did you need a reference to the IASKAppSettingsViewController in this notification?

**Comment by GarethShapiro** [comment]
I work on a large application.  At the time we were using more than one instance of IASKAppSettingsViewController and we needed to know which one changed a setting.

It seemed like an innocuous enough request as : 

1)  The key is also included in the userInfo and so the change would not make anything unavailable that was so before hand.

2)  This is the correct use of the object parameter as per Apple's docs.
**anObject** _The object posting the notification._
https://developer.apple.com/reference/foundation/nsnotificationcenter/1410608-postnotificationname?language=objc

Apologies for missing one.

**Comment by 0xced** [comment]
> Functionality-wise the delta didn't justify a 3.0.

I understand your feeling, but that’s not how semantic versioning works. I really don’t won’t to blame anyone here, I just like to raise awareness to help everyone build a better software ecosystem.

**Comment by futuretap** [comment]
You're right, thanks for the reminder. I was coming from a public app mindset but really, versioning frameworks should follow different rules.

**Pull request merged**
