### PR TITLE
Added regex input validation option

### PR DESCRIPTION
**Pull request by 696GrocuttT**

### CODE REVIEW

**Comment by futuretap** [comment]
Seems useful. Can you fix a few things?

- fix the build error (see Travis Details)
- prefix the constant (`IASKRegex` instead of just `Regex`)
- add a paragraph to the Readme explaining the feature
- add a sample to the sample app

Also, if you could use dot notation for property accesses, that would be terrific. (We do that at least for new code we add.)

Thanks!

**Comment by 696GrocuttT** [comment]
Great, I'll get on it, but it might be the weekend before I can get the fixes done.

Tom

**Comment by 696GrocuttT** [comment]
I've done the fixes you asked for apart from updating the sample app. Why I try and compile it I get the following error:
/Users/tgrocutt/Documents/gitHub/InAppSettingsKit/InAppSettingsKitSampleApp/CustomSubviewController.m:19:9: fatal error: 'InAppSettingsKit/IASKSpecifier.h' file not found
#import <InAppSettingsKit/IASKSpecifier.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Is there a trick to getting the dependencies between the sample app and the InAppSettingsKit library working? If you can point me in the right direction to get it to build I'll add a regex example to it.

Thanks

Tom

**Comment by futuretap** [comment]
I can't reproduce this error. Have you opened the .xcworkspace and built the `Sample App` target?

**Comment by 696GrocuttT** [comment]
Sorry, for some reason I didn't see the workspace file. The latest version I pushed should address all the changes you requested. Let me know if you want anything else changing.

**Comment by 696GrocuttT** [comment]
Is there anything else you need changing before this is merged? All your requested changes have been made.

**Comment by futuretap** [comment]
Merged. Thanks for the changes and sorry for taking so long, I was traveling.

Btw, when I played with the sample, I found it a bit unintuitive that the user's edit is simply replaced with the old value without any UI indicating so. We might think about shaking the textfield/cell or displaying an alert. Perhaps we should post a suitable Notification including the cell in the userInfo dictionary so the dev can customize the failure UX. What do you think?

**Comment by 696GrocuttT** [comment]
Sounds interesting. I'll have a go and see what I can do.

Tom

**Pull request merged**
