### PR TITLE
Adds support for Swift Package Manager

### PR DESCRIPTION
**Pull request by mmllr**

### CODE REVIEW

**Comment by futuretap** [comment]
Did you forget to include `IASKViewController.h` in `IASKAppSettingsViewController.m`?

**Comment by futuretap** [comment]
Thanks for your work on SPM! Could you do me a favor and add a paragraph in the README on how to include it using SPM?

**Comment by futuretap** [comment]
Thanks for the PR, I've published a new version with it and fixed two issues (CocoaPods was broken and one .h file missing for SPM).

**Comment by mmllr** [comment]
Great!, Thank you very much! SPM section of README.md in line 43 could be changed as follows:

```.package(name: "InAppSettingsKit", url: "https://github.com/futuretap/InAppSettingsKit.git", .upToNextMajor(from: "3.1.6"))```

Shall I make another pull request?

**Comment by futuretap** [comment]
Hm, that would mean users won't receive a 4.0 automatically. Not sure if we want to recommend that. Also, having to update the README simultaneously is dangerous and could be easily forgotten.

Imo, the Xcode UI approach is more convenient anyway.

**Pull request merged**
