### PR TITLE
Changes to structure to better support SPM when used with Tuist

### PR DESCRIPTION
**Pull request by hisaac**
Using the current version (3.3.3) of InAppSettingsKit with Xcode's Swift Package Manager integration, things work as expected. I ran into issues when trying to use it via [Tuist](https://tuist.io)'s SPM integration though, stemming from the way the Objective-C headers were being included into the package.

Primarily what I've done is just move files around into the default locations that SPM expects for Objective-C libraries (and then some small changes to support the file moves in the included Xcode projects and `.podspec`). All code goes in `Sources/InAppSettingsKit/`, and Objective-C headers go in `Sources/InAppSettingsKit/include/`. Doing it this way removes the need for the `InAppSettingsKit.h` header file, and allows for simplifying the `Package.swift` file by removing the need for custom target settings.

I understand this is somewhat of an edge case, but I believe the change is not breaking, and conforming to Apple's defaults is generally easier in the long run anyway.

Note: I am not using this library via CocoaPods, so I cannot test that. `pod spec lint` does succeed though, so conceivably that means the changes will work fine.

Any thoughts on this change?

### CODE REVIEW

**Comment by diederich** [comment]
hey @hisaac - thanks for the PR! 🙏 We like the direction! 
I'll look into this early next week. My hunch is to clean things up a little, completely drop the `xcodeproj` for the static library & the framework build (and thus also Carthage), and just rely on SPM. WDYT?

The SPM setup looks good - the resources might gone missing though?

**Comment by hisaac** [comment]
Good question on the Resources bit. Since I moved them to the default path that SPM expects — `Sources/<package name>/Resources/` — you don't need to define them manually in the `Package.swift` file. Same with the headers going in `Sources/<package name>/include`, that's where SPM expects them to be so you don't have to define it.

The Resources directory does show up for me when I import the package into an Xcode project:

Screen Shot 2021-09-17 at 3 03 53 PM

That said, I haven't specifically tested the Resources, so please do check my work on that.

As for dropping Carthage, I personally would continue to support it if it isn't too much work. It's definitely falling out of fashion, but I think there are still a fair amount of people using it. Obviously up to y'all though!

**Comment by diederich** [comment]
Thanks @hisaac !

> Good question on the Resources bit. Since I moved them to the default path that SPM expects — Sources/<package name>/Resources/ — you don't need to define them manually in the Package.swift file. 

Close! :-) It's the `defaultLocalization` that makes it work: https://developer.apple.com/documentation/swift_packages/localizing_package_resources
Once that's part of the `Package.swift` file, SPM expects the localized resource directories in the `Resources/*.lproj` folders.

> As for dropping Carthage, I personally would continue to support it if it isn't too much work. It's definitely falling out of fashion, but I think there are still a fair amount of people using it. Obviously up to y'all though!

Fair :-) We've kept it for now, but the sample app's not using the `xcodeproj` anymore, but is now also based on SPM.
I've also moved the Tests over to the default location. 

I've kept your commits as-is, and pushed one more on top: #462

**Comment by hisaac** [comment]
> Close! :-) It's the `defaultLocalization` that makes it work: [developer.apple.com/documentation/swift_packages/localizing_package_resources](https://developer.apple.com/documentation/swift_packages/localizing_package_resources)
> Once that's part of the `Package.swift` file, SPM expects the localized resource directories in the `Resources/*.lproj` folders.

Well I'm glad you checked my work then! I've never worked with localized resources in Swift Packages before, so this is good to know. Thanks. 👍

**Pull request closed without merging**
