### PR TITLE
Extended IASKAppSettingsWebViewController with 3 new IASK parameters

### PR DESCRIPTION
**Pull request by funnel20**
See: https://github.com/futuretap/InAppSettingsKit/issues/504

### CODE REVIEW

**Comment by funnel20** [comment]
@futuretap It's ready. Please test thoroughly.
After you confirm or any edits, I will update the documentation.

**Comment by futuretap** [comment]
Sorry for the long delay. Code looks and works fine! Can you also update the README? Indeed, we’ll release a 3.8.0 with the changes.

**Comment by funnel20** [comment]
@futuretap Thanks for the validation. I'll update the docu later today in the PR, so you can Release whenever you are ready.

**Comment by futuretap** [comment]
Thanks for your work, it’s included in the 3.8 release.

**Comment by funnel20** [comment]
@futuretap You're welcome, I'll update my apps when I'm back from holiday. Please note that in https://github.com/futuretap/InAppSettingsKit/releases the **Latest version** mark is still at 3.7.0

**Comment by futuretap** [comment]
Thanks, fixed!

**Pull request closed without merging**
